### ISSUE TITLE
Well trained model on COCO train 2014?

### ISSUE THREAD

**Issue by ivy94419** [DeepRNN/image_captioning#33]
This link can not open now. 
![image](https://user-images.githubusercontent.com/4054390/42855712-5ffb5eb2-8a74-11e8-9cdf-a884f21ced9c.png)

Could somebody share the well trained model the author provided? 
Or has somebody already trained on your own computers and save the model?

Thanks very much!

**Comment by rola93** [comment]
Hello! I downloaded it yesterday from [here](https://app.box.com/s/xuigzzaqfbpnf76t295h109ey9po5t8p) (taken from Readme.md). 

Perhaps you should try again. If it doesn't work, then [try with this](https://drive.google.com/file/d/15zuKd4ERMw2SZqBF33xLJoY9NNoHZKz5/view?usp=sharing) (I uploaded it in Drive since it's too big to attach here)

**Comment by ivy94419** [comment]
@rola93  Sorry for late response, thank you !!!

**Comment by chansongoal** [comment]
Did you get the same results as the author claimed?

**Comment by rola93** [comment]
@chansongoal I don't remember having checked exactly that (it was almost a year ago) but the results look good
